---
title: "Experts"
---

Below is the list of our experts:

+-----------------------------------------------------------------------------------+--------------------------------+
| Experts                                                                           | Areas                          |
+===================================================================================+================================+
| Prof Dr Nyi Nyi Naing \@ Syed Hatim Noor<br> syedhatim\@unisza.edu.my             |                                |
+-----------------------------------------------------------------------------------+--------------------------------+
| Assoc Prof Dr Aniza Binti Abd Aziz<br>anizaabdaziz\@unisza.edu.my                 |                                |
+-----------------------------------------------------------------------------------+--------------------------------+
| Assoc Prof Dr San San Oo<br>sansanoo\@unisza.edu.my                               |                                |
+-----------------------------------------------------------------------------------+--------------------------------+
| Assoc Prof Dr Intan Suhana Munira binti Mat Azmi<br> ismunira\@unisza.edu.my      | -   Community Dentistry        |
|                                                                                   | -   Public Health              |
+-----------------------------------------------------------------------------------+--------------------------------+
| Dr Nik Nor Ronaidi Bin Nik Mahdi<br> ronaidimahdi\@unisza.edu.my                  | -   Occupational Health        |
|                                                                                   | -   Environmental Health       |
|                                                                                   | -   Intermediate Biostatistics |
+-----------------------------------------------------------------------------------+--------------------------------+
| Dr Mohd Ihsanuddin Bin Abas<br> ihsanuddinabas\@unisza.edu.my                     | -   Health Management          |
|                                                                                   | -   Health Economics           |
|                                                                                   | -   Elderly Health             |
+-----------------------------------------------------------------------------------+--------------------------------+
| Dr Mazlan Bin Haji Abdullah<br>mazlanabdullah\@unisza.edu.my                      | -   Occupational Health        |
|                                                                                   |                                |
|                                                                                   | -   Health Economics           |
+-----------------------------------------------------------------------------------+--------------------------------+
| Dr Myat Moe Thwe Aung<br>myatmoe\@unisza.edu.my                                   |                                |
+-----------------------------------------------------------------------------------+--------------------------------+
| Dr Megat Mustaqim Bin Megat Iskandar<br>megatmustaqim\@unisza.edu.my              |                                |
+-----------------------------------------------------------------------------------+--------------------------------+
| Dr Tengku Muhammad Hanis Bin Tengku Mokhtar<br> tengkuhanismokhtar\@unisza.edu.my | -   Medical Statistics         |
|                                                                                   | -   Machine Learning           |
+-----------------------------------------------------------------------------------+--------------------------------+
